version: '3.3'

services:
  wordpress:
    image: soderlind/nettsteder-docker
    volumes:
      - ${WEBAPP_STORAGE_HOME}:/home/site/wwwroot
    ports:
      - "8000:80"
    restart: always

  redis:
    image: redis:5.0.9-alpine
    restart: always